### ISSUE TITLE
RouteName property gives ember.warn assertion failed error

### ISSUE THREAD

**Issue by SowmyaManohar** [onechiporenko/ember-models-table#314]
[Request] Please elaborate how to use routeName property
Got this error while using routeName property:
Tried to use routeName from usermanagement page to profile/id page of my app.

Error: Assertion Failed: When calling `warn` you must provide an `options` hash as the third parameter. 
 `options` should include an `id` property.↵    at new EmberError (http://localhost:4200/assets/vendor.js:28632:25)↵  
 at assert (http://localhost:4200/assets/vendor.js:28875:15)↵ 
 at warn (http://localhost:4200/assets/vendor.js:29166:27)↵  
 at Class._invoke (http://localhost:4200/assets/vendor.js:31749:47)↵   
 at sendEvent (http://localhost:4200/assets/vendor.js:37372:18)↵    
 at Class.trigger [as _super] (http://localhost:4200/assets/vendor.js:52319:33)↵   
 at Class.trigger (http://localhost:4200/assets/vendor.js:60707:19)↵ 
 at Class.superWrapper [as trigger] (http://localhost:4200/assets/vendor.js:58698:22)↵  
 at Backburner._run (http://localhost:4200/assets/vendor.js:25053:35)↵   
 at Backburner._join (http://localhost:4200/assets/vendor.js:25031:29)"

using ember 3.0

**Comment by SowmyaManohar** [comment]
Updating to ember 3.1.2 , the error disappeared , but i still get a warning  WARNING: This link-to is in an inactive loading state because at least one of its parameters presently has a null/undefined value, or the provided route name is invalid. 
using routeName:"profile" 
any help?

**Comment by SowmyaManohar** [comment]
This is because the this addon expects id , and my code passed as _id . After changing to id , it worked.
